site_name: CH376 LIB 2025.4 DOCUMENTATION

markdown_extensions:
#     - pymdownx.highlight
#     - pymdownx.inlinehilite
    - pymdownx.tabbed:
        alternate_style: true
#     - pymdownx.snippets
#     - pymdownx.critic
#     - pymdownx.caret
#     - pymdownx.keys
#     - pymdownx.mark
#     - pymdownx.tilde
#     - attr_list
#     - md_in_html
    - admonition
#     - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
#     - tables
#     - pymdownx.emoji:
#         emoji_index: !!python/name:materialx.emoji.twemoji
#         emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
 - git-revision-date
 - search
 - markmap
#  - mkdocs-video

dev_addr: '172.30.72.43:8002'

theme:
    name: material
    features:
      - search.suggest
      - search.highlight
      - search.share
nav:
    - Introduction: index.md
    - Versions:
        - 2024.2:
            - Assembly: 2024.2/index.md
            - ch376.inc: 2024.2/ch376.inc.md
            - C: 2024.2/c.md

    # - Routines:
    #     - ch376_check_exist: api/ch376_check_exist.md
    #     - ch376_dir_create: ch376_dir_create.md
    #     - ch376_disk_capacity: ch376_disk_capacity.md
    #     - ch376_disk_mount: ch376_disk_mount.md
        # - ch376_disk_query
        # - ch376_file_close
        # - ch376_file_create
        # - ch376_file_erase
        # - ch376_file_open
        # - ch376_get_descr
        # - ch376_get_file_size
        # - ch376_ic_get_ver
        # - ch376_lib_version
        # - ch376_reset_all
        # - ch376_seek_file
        # - ch376_set_address
        # - ch376_set_config
        # - ch376_set_file_name
        # - ch376_set_usb_addr
        # - ch376_set_usb_mode
        # - ch376_set_usb_speed
        # - ch376_wait_response

# extra_css:
#     - stylesheets/extra.css
# extra:
#     social:
#         - icon: fontawesome/brands/twitter
#           link: https://twitter.com/OrixTwil
#         - icon: fontawesome/brands/youtube
#           link: https://www.youtube.com/user/jede06600/videos
